<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Hubs\**" />
    <Compile Remove="Models\Attribution\**" />
    <Compile Remove="Models\Portfolio\**" />
    <Content Remove="Hubs\**" />
    <Content Remove="Models\Attribution\**" />
    <Content Remove="Models\Portfolio\**" />
    <EmbeddedResource Remove="Hubs\**" />
    <EmbeddedResource Remove="Models\Attribution\**" />
    <EmbeddedResource Remove="Models\Portfolio\**" />
    <None Remove="Hubs\**" />
    <None Remove="Models\Attribution\**" />
    <None Remove="Models\Portfolio\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="HtmlSanitizer" Version="9.1.893-beta" />
    <PackageReference Include="Konscious.Security.Cryptography.Argon2" Version="1.3.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="8.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Protocols.NewtonsoftJson" Version="8.0.3" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
    <PackageReference Include="System.Data.SqlClient" Version="4.8.6" />
    <PackageReference Include="System.DirectoryServices" Version="8.0.0" />
    <PackageReference Include="System.Security.Cryptography.Cng" Version="5.0.0" />
  </ItemGroup>

</Project>
